######################################################################
# Automatically generated by qmake (3.0) Thu Mar 7 19:39:42 2019
######################################################################

TEMPLATE = app
TARGET = LoTo
INCLUDEPATH += .

QT += core gui
QT += widgets

# Input

INCLUDEPATH += ../include \

HEADERS += ../include \
           ../include/executor.h

SOURCES += ../src/executor.cpp

RESOURCES += \
    ../resources/resources.qrc

