######################################################################
# Automatically generated by qmake (3.0) Thu Mar 7 19:39:42 2019
######################################################################

TEMPLATE = app
TARGET = executor
INCLUDEPATH += .

QT += core gui
QT += widgets

# Input
SOURCES += executor.cpp
HEADERS += executor.h
